### ISSUE TITLE
Consider renaming to something not "blind signature"

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-blind-signatures#1]
It's not the most inclusive term, though it is the established term in the literature.

**Comment by FredericJacobs** [comment]
We of course want to keep that discussion open and would welcome input on that from the broader community.

From #70:


> The term being widely used in the academic literature makes it hard to move away from it without causing some confusion about what our scheme implements.

> We also thought through about what it was referring to and got some interesting inputs from persons in the blind community such as:
> I'd even argue that in the case of the examples you mention it's an entirely appropriate use of the word because it describes the same thing - a situation in which someone does not have access to all their sensory characteristics or is not able to use all their sensory characteristics.
We considered "unlinkable signatures" to emphasize that between signing and verification, the signature should not be linkable but it doesn't convey all the nuance we were hoping for.

**Comment by chris-wood** [comment]
[Oblivious signatures](https://link.springer.com/content/pdf/10.1007/3-540-58618-0_62.pdf) _might_ also work, but the definition would need to stretch somewhat. Or we could just describe in words what this thing does, i.e., "private RSA signature computation," and note (just once) that this is referred to as a "blind signature" in the literature? 

One small downside I see is that not using the established name runs the risk of this type of specification flying under the radar. For example, a quick search for "blind signatures" might not reveal this specification, even though it may be what you're looking for.

**Comment by chris-wood** [comment]
Closing as proposed in IETF 111.
