### ISSUE TITLE
Remove MTI normative requirements

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-blind-signatures#103]
In hindsight, it's not really appropriate for a CFRG spec, which doesn't apply to any particular protocol, to enforce any algorithm requirements. That should be done in applications that use this specification. We can certainly recommend sane defaults, but a normative MUST is too much.

**Comment by dvorak42** [comment]
+1. Looking at implementing this, having the SHA-384 configuration as an MTI adds some unused bits. Unless there's a good reason to require at least that size hash? Though even then a recommendation instead of a MTI seems preferable.
