### ISSUE TITLE
Expand discussion about which interface to use 

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-blind-signatures#117]
... in the main document! Not in the security considerations.

**Comment by chris-wood** [comment]
Here's how I propose we deal with this:

1. Describe the protocol in terms of the three main functions, sort of as we do today, folding sections 5.1 into 5.
2. Move the salted interface into the API considerations section, as a subsection.
3. Add text which says that the salted interface is RECOMMENDED (pointing to security considerations), but the internal functions can be used directly if you know what you're doing.

@FredericJacobs, @jedisct1: thoughts?

**Comment by FredericJacobs** [comment]
Sounds good. I think we need to highlight that the other one can be used only if the message is a fully random high-entropy

**Comment by jedisct1** [comment]
But then we'll have to clarity what we mean with high-entropy in this context.

**Comment by chris-wood** [comment]
Slightly reworked proposal based on @davidben's feedback:

1. Describe the protocol in terms of the three main functions, sort of as we do today, folding sections 5.1 into 5.
2. Introduce a new section that describes the two named primitives he recommends.
3. Add text which says that the salted primitive is RECOMMENDED (pointing to security considerations), and the deterministic function can be used directly if you know what you're doing.

@FredericJacobs, @jedisct1: thoughts? Note that this will break Privacy Pass issuance which uses the internal functions directly with a non-empty salt (FYI @tfpauly), but we can simply change that spec without any concern. (This won't affect token verifiers, since they don't care if the PSS salt is empty or not.)

**Comment by davidben** [comment]
Ah, didn't realize that's what Privacy Pass was using. (I haven't been following.) I just got those two primitives from {#pss-options}, on the assumption those were the two modes that people wanted. If that's not right, I don't have any particular preferences on which or how many primitives to provide. (I mean, the fewer the better, but if you need multiple things then don't let me stop you from having multiple things.)

The overall feedback was more that the presentation in the document was confusion. And, in general, giving names to the things you want them to use has worked well (and having a miscellaneous collection of blocks to assemble arbitrarily [has not](https://www.imperialviolet.org/2022/03/15/pickingparameters.html)), so I think it's good to express the schemes that way.

**Comment by chris-wood** [comment]
> The overall feedback was more that the presentation in the document was confusing. And, in general, giving names to the things you want them to use has worked well (and having a miscellaneous collection of blocks to assemble arbitrarily [has not](https://www.imperialviolet.org/2022/03/15/pickingparameters.html)), so I think it'd help to express the schemes that way.

Yep, that's understood. This isn't really a "breaking" change in practice since Privacy Pass isn't really specific about _which_ version of this protocol to use. This proposed change would just require the document to be specific, which is an overall improvement for both!
