### ISSUE TITLE
Mix-matched cases and other nits

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-blind-signatures#120]
> It's silly to have both kLenInBytes and kLenInBits.  Just pick one and 
> compute the other from it.
>
> Just from an aesthetic point of view, camel case or snake case, pick one.

>  - All occurrences of "an byte string of length 32 bytes" -> "a 32-byte 
> string"

**Comment by chris-wood** [comment]
@FredericJacobs @jedisct1 unless there are objections, I propose converging on snake case.

**Comment by FredericJacobs** [comment]
Sounds reasonable to me

**Comment by jedisct1** [comment]
Sounds good.

**Comment by FredericJacobs** [comment]
I think we can close this, since it was merged in #129

**Comment by chris-wood** [comment]
There's still inconsistencies in the case, so let's keep this open for now. We can address it in parallel with the rest of the procedural work for the document. I'll own this issue.
