### ISSUE TITLE
Case match EMSA-PSS-ENCODE errors

### ISSUE THREAD

**Issue by martinthomson** [cfrg/draft-irtf-cfrg-blind-signatures#147]
EMSA-PSS-ENCODE is defined with:

```
   Errors:  "Encoding error"; "message too long"
```

But this specification says:

```
Errors:
- "message too long": Raised when the input message is too long.
- "encoding error": Raised when the input message fails encoding.
```

These strings are not identical.

**Comment by chris-wood** [comment]
If by "not identical" you mean that "Encoding error" in RFC8017 is capitalized, that's true, but the text description in that document uses "encoding error." I suspect "encoding" being capitalized was a mistake. I think what we have is correct. But we should note that both errors from from EMSA-PSS-ENCODE.
