### ISSUE TITLE
Randomization appears without context or rationale

### ISSUE THREAD

**Issue by martinthomson** [cfrg/draft-irtf-cfrg-blind-signatures#148]
[Section 5](https://cfrg.github.io/draft-irtf-cfrg-blind-signatures/draft-irtf-cfrg-rsa-blind-signatures.html#section-5) says *what* and *how* in ways that seem to be pretty solid, but doesn't contextualize the mechanism at all.  [Section 6](https://cfrg.github.io/draft-irtf-cfrg-blind-signatures/draft-irtf-cfrg-rsa-blind-signatures.html#section-6) doubles down on this and defines message formats that include randomization.

However, there is also nothing in preceding sections that might indicate why you might want to do this.

It is my understanding that the definition of message content is application-specific, which might interact poorly with any randomization scheme that is applied without considering those interactions.  One does not simply randomize messages without understanding what effect that randomization might have on the consumer of the message.

The definitions in [Section 6](https://cfrg.github.io/draft-irtf-cfrg-blind-signatures/draft-irtf-cfrg-rsa-blind-signatures.html#section-6) appear to run counter to the goal of using an off-the-shelf RSASSA-PSS verifier, because they require that the consumer understand that randomization has occurred.

Furthermore, the notes on use don't really scope the applicability of the mechanisms.  I am unable to use the text in this document to determine why randomization or not is necessary because I don't know where this might be applied.  One application is cited, but that seems to be just an example: what system properties are necessary for the overall design to be applicable?  And, what subset of those cases demand the use of randomization?

The goal here appears to be one that is motivated by Privacy Pass use cases, where a single message might need to be used multiple times but also be indistinguishable from each other.  It might be that there are no cases where having a signing oracle that doesn't see what it signs makes sense outside of this sort of anonymous ticket vending protocols, but the draft appears to assume this setting without directly saying so.

Consequently, without leaning heavily on an assumption that this is for Privacy Pass, these two sections were very hard to process.

**Comment by chris-wood** [comment]
This is a recurring comment amongst people. I've been thinking about how to address this, and here's my current proposal.

1. Add the message randomization step as an explicit, but optional, part of the core protocol description as described in [this PR](https://github.com/cfrg/draft-irtf-cfrg-blind-signatures/pull/165).
2. Move the message randomization section into the core protocol section, before the description of Blind. 
3. Shuffle the motivating text around from the named variants section to the message randomization section, so it's clear what the function does and why it's used.

@martinthomson, @FredericJacobs, @jedisct1: what do you think?
