### ISSUE TITLE
RFC8017 error handling

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-blind-signatures#157]
Section 4.2
I wonder if the error handling here makes sense. RSASP1 checks the
following: "If the message representative m is not between 0 and n - 1,
output "message representative out of range" and stop."
This makes steps 1 and 3 unnecessary unless I'm missing something.
Consistently raising errors from the functions called from RFC 8017 in all
these sections would be nice so implementers know how to handle them.

**Comment by jedisct1** [comment]
Indeed, that seems to be redundant.
