### ISSUE TITLE
Constants or parameters

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-blind-signatures#160]
Section 4.1
 - All RSABSSA variants from Section 6 appear to use SHA-384 as the hash function, and MGF1. Should we indicate hash and mgf as parameters if they are held constant? I see that they are options in RFC8017, but if they are held constant in the RSABSSA uses, I'd avoid listing them as options until they need to vary.
 
Section 4.3
 - Same notes on hash and MGF1 from 4.1 feedback

**Comment by jedisct1** [comment]
I'd be all for not making them parameters.

That simplifies implementations, as they can hardcode them.

**Comment by chris-wood** [comment]
I think I'd prefer to keep things as-is for now. If we decide in the future that we need new named variants, all we need to do is introduce them without changing any of the function descriptions. But at the end of the day this is purely editorial, and I don't think this will have any meaningful impact on implementations.

**Comment by chris-wood** [comment]
Unless there are strong objections to change this, let's close it. Anyone should feel free to comment on this or re-open it if they disagree, and we can discuss it.
