### ISSUE TITLE
VOPRFs as motivation

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-blind-signatures#179]
In Section 1, [I-D.irtf-cfrg-voprfs] is a broken reference.
Interestingly, Section 1 motivates this document with, "Specifically,
VOPRFs are not necessarily publicly verifiable", but
draft-irtf-cfrg-voprf-16 (which is presumably what the dangling link is
supposed to point to) _is_ publicly verifiable
(https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-voprf-16#section-2.2.2).
Is there another motivation for using RSA instead of
draft-irtf-cfrg-voprf-16?  Is it just the "in such a way that the
resulting (unblinded) signature can be verified with a standard RSA-PSS
library"?  As you point out here, VOPRFs are strongly related to
deterministic blind signatures.  Should VOPRFs be discussed in Section
8.7?

**Comment by chris-wood** [comment]
I think this comes from a confusion about "public verifiability" means for VOPRFs, so we can probably improve the text here.

**Comment by chris-wood** [comment]
Upon re-reading the text, I don't think any changes are needed here. It seems clear to me that public verifiability means that one can verify an output (signature) using only public information, which is something a VOPRF does not provide.

**Comment by jedisct1** [comment]
I don't think changes are needed either.

**Comment by FredericJacobs** [comment]
Agreed on scoping on public verifiability

**Comment by chris-wood** [comment]
Let's close this then.
