### ISSUE TITLE
Confirm that results from BNPS03 apply to this construction

### ISSUE THREAD

**Issue by FredericJacobs** [cfrg/draft-irtf-cfrg-blind-signatures#45]
From the security section:

> Bellare et al. {{?BNPS03=DOI.10.1007/s00145-002-0120-1}} proved security of Chaum's original blind signature scheme based on RSA-FDH based on "one-more-RSA-inversion." Note that the design in this document differs only in message encoding, i.e., using PSS instead of FDH. [[OPEN ISSUE: confirm that results from BNPS03 apply to this construction]]

**Comment by chris-wood** [comment]
@FredericJacobs: Given [Mihir's message on the list](https://mailarchive.ietf.org/arch/msg/cfrg/sGQOVtmxAEeqM0nBF2M4Kn_-LtM/), do we think any more work is needed here?
