### ISSUE TITLE
Emphasize randomness importance

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-blind-signatures#55]
From Jeff Burdges on the list:

> It’s critically important the blinding factor r be a uniformly random 
> integer mod n, which I think deserves more emphasis than you give.  
> There is an easy deanonymization attack if r were say generated a 
> random integer mod 2^{floor(log2 n)}.  You hould emphasize that 
> random_integer should be instantiated with a CSPRNG and rejection 
> sampling, maybe even specify the rejection sampling algorithm starting 
> with shake or chacha.

**Comment by jedisct1** [comment]
This is a very good point.

Specifying a rejection sampling algorithm sounds clearly out of scope, though.

Rejection sampling can be cited as a way to get a uniformly distributed integer, but giving too much details can lead to confusion.

In practice, what most people really want is just use whatever function their big number library already provides for that purpose -- and, with big numbers, doing anything else would be more complicated anyway.

**Comment by jedisct1** [comment]
May rename `random_integer` to `random_integer_uniform` so that it's hard to miss, even if the Notation section was overlooked?

The definition of the function may actually cause more confusion.

Virtually all implementations of a `random_integer(M, N)` function return `R` so that `M <= R < N`, not `M < R <= N` as we define it. Not a big deal, though.

**Comment by chris-wood** [comment]
I'm also hesitant to go into more detail about the implementation of this function. 

> Maybe rename random_integer to random_integer_uniform so that it's hard to miss, even if the Notation section was overlooked?

Yeah, that would certainly make the requirement more clear, and might be enough?

**Comment by FredericJacobs** [comment]
[ ] we should add a line in the security considerations section linking to the paper Jeff mentioned on the IETF mailing list explaining the importance of the uniform distribution for choosing the blind.

**Comment by tjesi** [comment]
I think it is good practice to check that `r` is valid before using it in any computations. It is valid if `gcd(r,n) = 1`, and then there will always exist an inverse. However, if `gcd(r,n) > 1` then you have found a factor of `n`, and hence, the parameters are broken, but I guess this will never happen in practice when choosing reasonable sizes for `n`.

**Comment by jedisct1** [comment]
It wouldn't hurt to do it. Checking that `r` is not `0` or one of the prime factors is very cheap. But in the specification, it may be reasonable to assume that the modular inversion function isn't completely broken.

If `r_inv` is not `r^-1`, `Finalize` would return an error, so the implications would be minimal anyway.

**Comment by tjesi** [comment]
Fair point, but then I would compute `r_inv` before using `r`, instead of afterwards.

**Comment by jedisct1** [comment]
@tjesi what do you think about https://github.com/chris-wood/draft-wood-cfrg-blind-signatures/commit/b55838ad941bcf7aa82c828844b9b8e02294868b ?

**Comment by tjesi** [comment]
I am satisfied 👍

**Comment by chris-wood** [comment]
@jedisct1, do you want to take this issue?

**Comment by jedisct1** [comment]
I take this.

**Comment by chris-wood** [comment]
@jedisct1 thanks! Do you think you can get to this before July 12 (IETF draft deadline day)?
