### ISSUE TITLE
Clarify salting options

### ISSUE THREAD

**Issue by smhendrickson** [cfrg/draft-irtf-cfrg-blind-signatures#71]
This issue is a summary of one discussed with the authors previously.

PSS implies a salt is included. This salt could be used to communicate information on the unblinded signed token. For some applications, this may not matter. For others, this could be used for a form of 'vote selling', where the salt is constructed in a non-random fashion but appears to the uninformed to be random. I'll refer to this as 'salt-signaling'.

Applications susceptible to salt-signaling may be better off requiring a zero-salt, which can be checked at verification time. This leaves only the token to communicate information with, which could be enforced by the application to be low-entropy.

Zero-salt reduces the security proof of PSS to an FDH, instead of binding it to the RSA proof, and therefor probably shouldn't be considered for every case.

With this in mind, should we prescribe two salting options in the spec? If we do, we'll need a concise description of the problem and what applications should consider when choosing a salting option.

**Comment by chris-wood** [comment]
Thanks for filing, @smhendrickson! I'd like to better understand the threat model here. If we are concerned about the salt being chosen maliciously, are we also concerned about the blind being chosen maliciously? It would seem that any doubt we have over the randomness of the PSS salt applies equally to the blind, and the security of this whole scheme seems to depend on that. Am I missing something?

**Comment by smhendrickson** [comment]
I agree both PSS and FDH require a secure random source to protect against a rigged blind.

The case I am concerned about is more subtle. A client (the blinder and holder of the blinding factor) might intentionally choose their salt to signal something later in the verification ledger. This might subvert a protocol designers desire to ensure signed tokens are low entropy, and can't be used for signaling by the client beyond the token content.

I'll use a simplified voting system as an example. Tokens in this case might be low-entropy values, like a simple enum, "candidate1" or "candidate2".  A voter constructs their token, blinds it, proves they can vote and gets it signed. Now they unblind their token, and send it for verification and recording. In verification, the ledger of votes and signatures is made public.

Now imagine one wants to sell their vote for a specific candidate. They could choose a specific salt to indicate to the candidate that they voted the correct way. That salt would appear in the public ledger.

In this case the source of randomness is secure. The client chose to subvert the protocol designers intent by signaling with the salt, instead of within the token where they couldn't signal and get away with it b/c the token was a trivial enum.

**Comment by chris-wood** [comment]
Thanks for clarifying! I think that makes sense. Applications which are concerned about this sort of covert channel may need to remove signals in the signature itself (including the salt) and the message. 

I'm comfortable introducing a zero-salt variant, but we would need to decide what "zero-salt" actually means. Is it a salt of zero length (empty string)? String of `Nh` bytes equal to zero? Something else? Most PSS APIs that I'm aware of tend to fall into one of two categories: specify the nonce length explicitly, or let it be automatically determined based on the corresponding hash function. The salt isn't typically provided by the application, so setting it to the empty string by marking the salt length as 0 might work [for some implementations](https://github.com/google/boringssl/blob/master/crypto/fipsmodule/rsa/padding.c#L618-L632), but might not work [for others](https://golang.org/src/crypto/rsa/pss.go?s=6332:6738#L225).

@FredericJacobs, @jedisct1: what do you think?

**Comment by FredericJacobs** [comment]
Mostly aligned with your comment @chris-wood.

We want to be interoperable with RSA-PSS signatures, so I suggest we keep a mode that uses the random salts. But we should add a security consideration about the risks of letting the client choose the salt and how it can be used for passing information to the verifier (although, I'm not convinced that in most use cases this is a concern).

As for verifying the "null salt", I think we could consider doing this in a way that is external to the RSA-PSS verification, for use cases where they want to use an unmodified RSA-PSS verify routing under the hood that doesn't allow to force the salt to be nonce through its API surface. So the higher-level would verify that the salt is null in the signature and then pass the payload to RSA-PSS verify.

**Comment by chris-wood** [comment]
> As for verifying the "null salt", I think we could consider doing this in a way that is external to the RSA-PSS verification, for use cases where they want to use an unmodified RSA-PSS verify routing under the hood that doesn't allow to force the salt to be nonce through its API surface. So the higher-level would verify that the salt is null in the signature and then pass the payload to RSA-PSS verify.

That would also work, and be purely an editorial change, but I _think_ @smhendrickson is advocating for this to be handled beneath the signature APIs for client. As in, I understood the request to be that clients can request a blind signature with a "blind salt," as opposed to requesting a blind signature with "this specific salt value that happens to be null." The former seems harder for developers to misuse, and perhaps less so for the latter.

**Comment by jedisct1** [comment]
Adding a "null salt" special case would complexity to the specification and to the APIs.

If client-chosen salts are a concern, maybe it would be better addressed with two distinct APIs. One as currently specified, and another one that could explicitly use FDH.

**Comment by chris-wood** [comment]
> One as currently specified, and another one that could explicitly use FDH.

By this do you mean one that picks the salt and then passes it to a PSS encoding function, or one that literally uses FDH in lieu of PSS? It would be a shame, I think, if signatures produced by this special case were not verifiable with PSS, so I would lean towards the former. 

At the end of the day, this seems to be mostly a question of what API is provided to clients. Is that right?

**Comment by jedisct1** [comment]
> As in, I understood the request to be that clients can request a blind signature with a "blind salt," as opposed to requesting a blind signature with "this specific salt value that happens to be null."

I'm not sure we all understood the request the same way. @smhendrickson, could you clarify?

**Comment by smhendrickson** [comment]
Chris has my request right. I was suggesting that we should provide two modes: one where salts are chosen randomly, and another where they are set to zero.

> As for verifying the "null salt", I think we could consider doing this in a way that is external to the RSA-PSS verification, for use cases where they want to use an unmodified RSA-PSS verify routing under the hood that doesn't allow to force the salt to be nonce through its API surface. So the higher-level would verify that the salt is null in the signature and then pass the payload to RSA-PSS verify.

@FredericJacobs makes a really good point here. The _verification_ logic could indeed be unmodified, as another layer of code could verify null salts.  This should make implementation much easier for most.

With this in mind, this request is reduced to API design during token creation. I'd prefer if we recommended implementers don't allow any salt to be passed in, as this makes it easier to salt-signal. Instead, if we can recommend a null salt option be available and explain the case, this might be sufficient. We can then also choose to prescribe null vs zero length salt.

**Comment by chris-wood** [comment]
Thanks for clarifying, @smhendrickson! I'll try and put together a PR based on this request for us to discuss further.
