### ISSUE TITLE
Add deterministic signature test vector

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-blind-signatures#73]
The single test vector in the document currently covers the case where sLen > 0. Since we admit both, we should also include a test vector where sLen = 0.

**Comment by jedisct1** [comment]
Hey Chris,

Do you need a hand with this?

**Comment by chris-wood** [comment]
If you have cycles to get to this before Friday, that would be great! I was hoping we could get this into the next draft version, which has a deadline of July 12.
