### ISSUE TITLE
Hash functions and salt length 

### ISSUE THREAD

**Issue by jedisct1** [cfrg/draft-irtf-cfrg-blind-signatures#75]
> Implementations MUST support PS384-encoding, using SHA-384 as Hash and MGF functions
> and sLen = 48, as described in RFC8230. It is RECOMMENDED that implementations also support
> encoding using SHA-384 as Hash and MGF functions and sLen = 0.

Reading this suggests that conformant implementations only have to support SHA-384, with sLen = 48 or sLen = 0, excluding other hash functions and salt lengths.

That wouldn't necessarily be a bad thing, both to keep APIs simple (parameters are reduced to keys and a "use deterministic padding" flag) and to improve interoperability (again, no parameters to agree on besides keys).

But do we want to allow for more flexibility (PS256, PS512, or arbitrary hash&salt length combinations)?

**Comment by chris-wood** [comment]
Yeah, fair point. What if we just RECOMMEND that one deterministic and one randomized variant be supported, and point to other documents like RFC8230 for relevant parameters?

**Comment by FredericJacobs** [comment]
The related question becomes whether we want to define "cipher suites" in a way.

eg. With 4096-bit keys, use SHA-384 as Hash Function and MGF, with a 48-byte salt.

I don't like the idea of having too much configurability with mix-and-matches of algorithms.

So I would be more in favour of supporting fixed sets of algorithms.

**Comment by jedisct1** [comment]
I'm not a big fan of cipher suites or configurability without a significant difference between available options.

It is very unlikely that an implementation wouldn't support the common RSA key sizes unless the document explicitly lists them.

In this context, the only parameters that could break interoperability are the Hash and MGF functions and salt length. Fixing them to {SHA-384, 48} for randomized padding and {SHA-384, 0} for the deterministic variant regardless of the key size would keep everything simple.

**Comment by chris-wood** [comment]
> In this context, the only parameters that could break interoperability are the Hash and MGF functions and salt length. Fixing them to {SHA-384, 48} for randomized padding and {SHA-384, 0} for the deterministic variant regardless of the key size would keep everything simple.

Agreed. Plus, unless we create a registry (which I don't think we should do), we really can't stop anyone from using other variants. Shall we close this issue out?

**Comment by jedisct1** [comment]
Yes, this can be closed. The document seems to be explicit enough.

Thanks for your input!
