### ISSUE TITLE
Consider widening scope

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-blind-signatures#83]
During the [RGLC adoption call conclusion message](https://mailarchive.ietf.org/arch/msg/cfrg/m1RB0XnelZ8qU1m8tdnhcsl93Ms/), Stanislav noted:

> At the same time, since there were some concerns about the constructions defined in the document, the scope of the draft might be generalized during further work. We seek volunteers who would like to work on the draft (considering not only RSA-based constructions, but, e.g., ElGamal based ones as well).

This issue tracks possibly widening the scope of the draft to support other signature schemes. 

In my opinion, I think we should close this issue. I consider the scope best left as-is. Blind BLS, for example, can be [added to the BLS draft](https://github.com/cfrg/draft-irtf-cfrg-bls-signature/issues/37), and [blind variants of Schnorr-based signatures](https://eprint.iacr.org/2019/877) that are considered safe can be more succinctly specified in a separate document. Adding either here runs the risk of making the specification more complex and difficult to understand (and therefore prone to implementation mistakes), which seems counter productive.

@FredericJacobs, @jedisct1: what do you think?

**Comment by jedisct1** [comment]
I'm in favor of keeping the document focused on RSA, and more generally on having a dedicated document for each signature type.

This makes the document more consistent and less confusing. It is also easier to maintain and review.

**Comment by chris-wood** [comment]
Closing as proposed in IETF 111.
