### ISSUE TITLE
Add check that m < n before step 3 of blind sign

### ISSUE THREAD

**Issue by FredericJacobs** [cfrg/draft-irtf-cfrg-blind-signatures#85]
We could check that m < n before doing step 3.

```
1. If len(blinded_msg) != kLen, raise "unexpected input size"
   and stop
2. m = OS2IP(blinded_msg)
3. s = RSASP1(skS, m)
```

**Comment by jedisct1** [comment]
Nod.

This is cheap, and if only for interoperability purposes (some implementations may perform a reduction, others may not), this is a good idea.
