### ISSUE TITLE
I2OSP vs IP2OS

### ISSUE THREAD

**Issue by jedisct1** [cfrg/draft-irtf-cfrg-blind-signatures#89]
Quoting Rich on the CFRG list:

> I kept getting thrown by the asymmetry between “OS2IP” and “I2OSP” – shouldn’t that latter be “IP2OS” ? (Yes know 8017/PKCS1.5 is at fault)

The asymmetry is indeed confusing.

On the other hand:

- The document references RFC8017 for the definition of the conversion functions. If we want to use different names, we have to define these functions ourselves.
- Given that the `P` stands for `primitive`, having it at the end makes sense.
- Without remembering what the initials stand for, the meaning of `I2OSP` and `OS2IP` is not obvious anyway. Using `IP2OS` instead of `I2OSP` doesn't feel like a major improvement.

So, in the context of RSA, I'd be in favor of keeping the RFC8017 function name.

**Comment by chris-wood** [comment]
Perhaps we could give these more descriptive names, `I2OSP ` => `IntToBytes` and `OS2IP ` => `BytesToInt`, and then just say that they're implemented with the RFC8017 functions? (Maybe that's what you meant by the first bullet.)

**Comment by jedisct1** [comment]
Yes! That would greatly improve clarity.
